---
apiVersion: tenantoperator.stakater.com/v1beta2
kind: Tenant
metadata:
  name: zeus
spec:
  editors:
    users:
      - emma-vu@nordmart.com
  namespaces:
    withTenantPrefix:
      - dev
      - stage
      - prod
  onDelete:
    cleanAppProject: true
    cleanNamespaces: false
  owners:
    users:
      - lucas-liu@nordmart.com
      - mto@stakater.com
  quota: medium
  viewers:
    users:
      - lila-forgac@nordmart.com
