---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: keycloak
spec:
  identityProviders:
    - mappingMethod: claim
      name: mto
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - email
            - upn
        clientID: openshift
        clientSecret:
          name: mto-iam-oauth-secret
        extraAuthorizeParameters:
          include_granted_scopes: 'true'
        extraScopes:
          - email
          - profile
        issuer: >-
          https://tenant-operator-keycloak-multi-tenant-operator.apps.tno1-ams.s9nghh76.lab.kubeapp.cloud/realms/mto
      type: OpenID
