apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-sync-operator
  namespace: {{ include "rh-group-sync-operator.namespace" . }}
  labels:
    {{- include "rh-group-sync-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rh-group-sync-operator.matchLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "rh-group-sync-operator.labels" . | nindent 8 }}
        {{- include "rh-group-sync-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: group-sync-operator-controller-manager
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --tls-cert-file=/etc/certs/tls/tls.crt
            - --tls-private-key-file=/etc/certs/tls/tls.key
          image: "quay.io/redhat-cop/kube-rbac-proxy:v0.11.0"
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
          volumeMounts:
            - mountPath: /etc/certs/tls
              name: tls-cert
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.kuberbacproxy.resources | nindent 12 }}
        - command:
            - /manager
          args:
            - --health-probe-bind-address=:8081
            - --metrics-addr=127.0.0.1:8080
            - --leader-elect
          image: "quay.io/redhat-cop/group-sync-operator:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          name: group-sync-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.manager.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: tls-cert
          secret:
            defaultMode: 420
            secretName: group-sync-operator-certs