apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: group-sync-operator-prometheus-k8s
  namespace: {{ include "rh-group-sync-operator.namespace" . }}
  labels:
    {{- include "rh-group-sync-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  verbs:
  - get
  - list
  - watch