apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "rh-group-sync-operator.labels" . | nindent 4 }}
    {{- include "rh-group-sync-operator.selectorLabels" . | nindent 4 }}
  name: group-sync-operator-controller-manager-metrics-monitor
  namespace: {{ include "rh-group-sync-operator.namespace" . }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: group-sync-operator-controller-manager-metrics-service.{{ (.Values.namespace).name | default .Release.Namespace }}.svc
  selector:
    matchLabels:
      {{- include "rh-group-sync-operator.selectorLabels" . | nindent 6 }}