---
apiVersion: tenantoperator.stakater.com/v1beta2
kind: Tenant
metadata:
  name: apollo
spec:
  commonMetadata:
    annotations:
      stakater.com/annotations: apollo
    labels:
      stakater.com/label: apollo
  editors:
    users:
      - ava-li@nordmart.com
  namespaces:
    withTenantPrefix:
      - build
      - dev
      - prod
  onDelete:
    cleanAppProject: true
    cleanNamespaces: true
  owners:
    users:
      - jasper-eriksson@nordmart.com
      - mto@stakater.com
  quota: large
  specificMetadata:
    - annotations:
        stakater.com/annotations-spec: apollo
      labels:
        stakater.com/label-spec: apollo
      namespaces:
        - build
    - annotations:
        stakater.com/annotations-spec-2: apollo
      labels:
        stakater.com/label-spec-2: apollo
      namespaces:
        - dev
  viewers:
    users:
      - milo-chaudhary@nordmart.com
