---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch-operator
  namespace: rh-openshift-gitops-instance
spec:
  project: default
  source:
    repoURL: 'https://redhat-cop.github.io/patch-operator'
    chart: patch-operator
    targetRevision: v0.1.9
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mto-hands-on
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
