---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rh-group-sync-operator
  namespace: rh-openshift-gitops-instance
spec:
  project: default
  source:
    repoURL: 'https://redhat-cop.github.io/group-sync-operator'
    chart: group-sync-operator
    targetRevision: v0.0.28
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mto-hands-on
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
