---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-mto-manager-binding
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: rh-openshift-gitops-instance
roleRef:
  kind: ClusterRole
  name: argocd-mto-manager
  apiGroup: rbac.authorization.k8s.io
